slice_name: Cervical Cancer Screening HC Raw Data
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 14__table
  viz_type: table
  slice_id: 32
  granularity_sqla: visit_date
  time_grain_sqla: P1D
  time_range: Last year
  query_mode: raw
  groupby: []
  all_columns:
  - client_id
  - client_name
  - gender
  - age
  - birthdate
  - id_poor
  - national_id
  - pmrs_id
  - covid_vaccination_id
  - nssf
  - ssn
  - passport_no
  - other_identifiers
  - province
  - district
  - commune
  - village
  - occupation
  - place_of_birth
  - ethnicity
  - marital_status
  - visit_start_date
  - visit_start_time_text
  - education
  - visit_end_date
  - visit_end_time
  - referred_from
  - has_referral_letter
  - payment_type
  - visit_district
  - visit_hf_code
  - visit_hf_name
  - is_screen_for_css
  - visit_province
  - hpv_test_result
  - cytology_test_result
  - address_zone
  - sex_debut
  - test_type
  - previous_pregnant
  - number_of_pregnancies
  - number_of_deliveries
  - number_of_miscarriages
  - treatment
  - smoked
  - corticosteroid_use
  - corticosteroid_use_duration
  - via_test_result
  - has_multiple_sex_partners
  - partner_has_multiple_sex_partners
  - history_stis
  - has_history_stis
  - current_stis
  - has_hiv
  - has_current_stis
  - hiv_treatment
  - coc_use_for_more_than_5_yrs
  - type_of_cancer
  - vulva_exam
  - vagina_exam
  - cervix_exam
  - family_history_cancer
  - bleeding_after_sex
  - other_physical_exam
  - cervix_text
  - uterus_text
  - vaginal_rectal_text
  - is_educated_for_css
  - hpv_result
  - vulva_text
  - scj_visibility
  - hpv_virus_type
  - number_of_quadrants
  - rectum_text
  - via_test_results
  - cc_reason_for_referral
  - aceto_white_ecto_cervix
  - cc_treatment_options
  - cc_appointment_date
  - is_educated_for_bs
  - cc_reason_for_appointment
  - sign_of_breast
  - bc_treatment
  - bc_reason_for_referral
  - bc_appointment_date
  - bc_reason_for_appointment
  - rf_hf_code
  - rf_hf_province
  - rf_hf_district
  - rf_hf_name
  - fallopian_text
  percent_metrics: []
  adhoc_filters: []
  order_by_cols:
  - '["visit_date", false]'
  row_limit: 5000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  page_length: 200
  show_cell_bars: false
  color_pn: true
  allow_rearrange_columns: true
  column_config:
    visit_start_time:
      d3TimeFormat: '%H:%M:%S'
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 8
  annotation_layers: []
query_context: '{"datasource":{"id":14,"type":"table"},"force":false,"queries":[{"time_range":"Last
  year","granularity":"visit_date","filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["client_id","client_name","gender","age","birthdate","id_poor","national_id","pmrs_id","covid_vaccination_id","nssf","ssn","passport_no","other_identifiers","province","district","commune","village","occupation","place_of_birth","ethnicity","marital_status","visit_start_date","visit_start_time_text","education","visit_end_date","visit_end_time","referred_from","has_referral_letter","payment_type","visit_district","visit_hf_code","visit_hf_name","is_screen_for_css","visit_province","hpv_test_result","cytology_test_result","address_zone","sex_debut","test_type","previous_pregnant","number_of_pregnancies","number_of_deliveries","number_of_miscarriages","treatment","smoked","corticosteroid_use","corticosteroid_use_duration","via_test_result","has_multiple_sex_partners","partner_has_multiple_sex_partners","history_stis","has_history_stis","current_stis","has_hiv","has_current_stis","hiv_treatment","coc_use_for_more_than_5_yrs","type_of_cancer","vulva_exam","vagina_exam","cervix_exam","family_history_cancer","bleeding_after_sex","other_physical_exam","cervix_text","uterus_text","vaginal_rectal_text","is_educated_for_css","hpv_result","vulva_text","scj_visibility","hpv_virus_type","number_of_quadrants","rectum_text","via_test_results","cc_reason_for_referral","aceto_white_ecto_cervix","cc_treatment_options","cc_appointment_date","is_educated_for_bs","cc_reason_for_appointment","sign_of_breast","bc_treatment","bc_reason_for_referral","bc_appointment_date","bc_reason_for_appointment","rf_hf_code","rf_hf_province","rf_hf_district","rf_hf_name","fallopian_text"],"orderby":[["visit_date",false]],"annotation_layers":[],"row_limit":5000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]}],"form_data":{"datasource":"14__table","viz_type":"table","slice_id":32,"granularity_sqla":"visit_date","time_grain_sqla":"P1D","time_range":"Last
  year","query_mode":"raw","groupby":[],"all_columns":["client_id","client_name","gender","age","birthdate","id_poor","national_id","pmrs_id","covid_vaccination_id","nssf","ssn","passport_no","other_identifiers","province","district","commune","village","occupation","place_of_birth","ethnicity","marital_status","visit_start_date","visit_start_time_text","education","visit_end_date","visit_end_time","referred_from","has_referral_letter","payment_type","visit_district","visit_hf_code","visit_hf_name","is_screen_for_css","visit_province","hpv_test_result","cytology_test_result","address_zone","sex_debut","test_type","previous_pregnant","number_of_pregnancies","number_of_deliveries","number_of_miscarriages","treatment","smoked","corticosteroid_use","corticosteroid_use_duration","via_test_result","has_multiple_sex_partners","partner_has_multiple_sex_partners","history_stis","has_history_stis","current_stis","has_hiv","has_current_stis","hiv_treatment","coc_use_for_more_than_5_yrs","type_of_cancer","vulva_exam","vagina_exam","cervix_exam","family_history_cancer","bleeding_after_sex","other_physical_exam","cervix_text","uterus_text","vaginal_rectal_text","is_educated_for_css","hpv_result","vulva_text","scj_visibility","hpv_virus_type","number_of_quadrants","rectum_text","via_test_results","cc_reason_for_referral","aceto_white_ecto_cervix","cc_treatment_options","cc_appointment_date","is_educated_for_bs","cc_reason_for_appointment","sign_of_breast","bc_treatment","bc_reason_for_referral","bc_appointment_date","bc_reason_for_appointment","rf_hf_code","rf_hf_province","rf_hf_district","rf_hf_name","fallopian_text"],"percent_metrics":[],"adhoc_filters":[],"order_by_cols":["[\"visit_date\",
  false]"],"row_limit":5000,"server_page_length":10,"include_time":false,"order_desc":true,"table_timestamp_format":"smart_date","page_length":200,"show_cell_bars":false,"color_pn":true,"allow_rearrange_columns":true,"column_config":{"visit_start_time":{"d3TimeFormat":"%H:%M:%S"}},"conditional_formatting":[],"extra_form_data":{},"dashboards":[8],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: a133510d-1fd5-405c-8db9-0ad187e7c73c
version: 1.0.0
dataset_uuid: 5457e2a2-5943-4b14-8a0e-878c7ba4bc8f
