slice_name: Dropout
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 6__table
  viz_type: pivot_table_v2
  granularity_sqla: date_started
  time_grain_sqla: P1D
  time_range: No filter
  groupbyColumns:
  - age_group
  groupbyRows:
  - gender
  metrics:
  - sum dm with hbp drop out
  - sum dm dropout
  - sum hbp dropout
  metricsLayout: ROWS
  adhoc_filters: []
  row_limit: 10000
  order_desc: true
  aggregateFunction: Sum
  rowTotals: true
  colTotals: true
  valueFormat: ~g
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 6
  annotation_layers: []
query_context: '{"datasource":{"id":6,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","granularity":"date_started","filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["age_group","gender"],"metrics":["sum
  dm with hbp drop out","sum dm dropout","sum hbp dropout"],"orderby":[["sum dm with
  hbp drop out",false]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"6__table","viz_type":"pivot_table_v2","granularity_sqla":"date_started","time_grain_sqla":"P1D","time_range":"No
  filter","groupbyColumns":["age_group"],"groupbyRows":["gender"],"metrics":["sum
  dm with hbp drop out","sum dm dropout","sum hbp dropout"],"metricsLayout":"ROWS","adhoc_filters":[],"row_limit":10000,"order_desc":true,"aggregateFunction":"Sum","rowTotals":true,"colTotals":true,"valueFormat":"~g","date_format":"smart_date","rowOrder":"key_a_to_z","colOrder":"key_a_to_z","conditional_formatting":[],"extra_form_data":{},"dashboards":[6],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: bb6a9f95-951c-4b31-b03d-a9c53fa34904
version: 1.0.0
dataset_uuid: 6fa56ea7-aa49-46cd-8ae8-f8c5d141e0c9
