slice_name: NCD RH EMR Raw Data
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 16__table
  viz_type: table
  slice_id: 48
  granularity_sqla: visit_date_time
  time_grain_sqla: P1D
  time_range: No filter
  query_mode: raw
  groupby: []
  metrics: []
  all_columns:
  - client_id
  - client_name
  - gender
  - age
  - id_poor
  - national_id
  - covid_vacination_id
  - pmrs_id
  - nssf
  - ssn
  - passport_no
  - other_identifiers
  - village
  - commune
  - district
  - province
  - country
  - phone_number
  - occupation
  - place_of_birth
  - ethnicity
  - marital_status
  - education
  - visit_date_time
  - hf_code
  - hf_name
  - visit_type
  - visit_province
  - visit_district
  - payment_type
  - referred_from
  - address_zone
  - has_referral_letter
  - tb_symptom_presence
  - refferred_tb
  - waist_circumference
  - weight
  - height
  - bmi
  - systolic
  - diastolic
  - pulse_rate
  - temperature
  - respiratory
  - spo2
  - fasting_blood_sugar
  - random_blood_sugar
  - ogtt_h1
  - ogtt_h2
  - hb1ac
  - haemoglobin
  - albumin
  - ketones
  - total_cholesterol
  - low_density_lipoprotein
  - high_density_lipoprotein
  - triglycerides
  - creatinine
  - creatinine_clearance
  - proteinuria
  - potassium
  - ace_inhibitor
  - sodium
  - ast_asat
  - alt_alat
  - smoking
  - quit_smoking
  - physical_activity
  - alcohol
  - left_foot_exam
  - right_foot_exam
  - left_eye_exam
  - right_eye_exam
  - cardiovacscular_exam
  - uro_gen_exam
  - ent_exam
  - respiratory_exam
  - gastro_intestinal_exam
  - skin_extremities_examination
  - cns_exam
  - mental_state_exam
  - abdominal_exam
  - others_exam
  - cvd_score
  - diagnosis_one
  - diagnosis_two
  - other_health_conditions
  - current_medical_complications
  - other_health_complications
  - current_therapy
  - started_on_medicine
  - other_recomendations
  - follow_up_date
  - reason_for_referral
  - diagnosed_for_dm
  - dm_treatment_before
  - dm_year_of_diagnosis
  - diagnosed_for_hbp
  - hbp_treatment_before
  - hbp_year_of_diagnosis
  - premature_heart_or_stroke_disease
  - diabetes_or_kidney_disease
  - tradition_medicine_use
  - previous_medical_complications
  - medical_history_other_health_complications
  - allergies_details
  - visit_end_date_time
  - drugs
  percent_metrics: []
  adhoc_filters: []
  order_by_cols: []
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  show_cell_bars: false
  color_pn: true
  allow_rearrange_columns: true
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 10
  annotation_layers: []
query_context: '{"datasource":{"id":16,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","granularity":"visit_date_time","filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["client_id","client_name","gender","age","id_poor","national_id","covid_vacination_id","pmrs_id","nssf","ssn","passport_no","other_identifiers","village","commune","district","province","country","phone_number","occupation","place_of_birth","ethnicity","marital_status","education","visit_date_time","hf_code","hf_name","visit_type","visit_province","visit_district","payment_type","referred_from","address_zone","has_referral_letter","tb_symptom_presence","refferred_tb","waist_circumference","weight","height","bmi","systolic","diastolic","pulse_rate","temperature","respiratory","spo2","fasting_blood_sugar","random_blood_sugar","ogtt_h1","ogtt_h2","hb1ac","haemoglobin","albumin","ketones","total_cholesterol","low_density_lipoprotein","high_density_lipoprotein","triglycerides","creatinine","creatinine_clearance","proteinuria","potassium","ace_inhibitor","sodium","ast_asat","alt_alat","smoking","quit_smoking","physical_activity","alcohol","left_foot_exam","right_foot_exam","left_eye_exam","right_eye_exam","cardiovacscular_exam","uro_gen_exam","ent_exam","respiratory_exam","gastro_intestinal_exam","skin_extremities_examination","cns_exam","mental_state_exam","abdominal_exam","others_exam","cvd_score","diagnosis_one","diagnosis_two","other_health_conditions","current_medical_complications","other_health_complications","current_therapy","started_on_medicine","other_recomendations","follow_up_date","reason_for_referral","diagnosed_for_dm","dm_treatment_before","dm_year_of_diagnosis","diagnosed_for_hbp","hbp_treatment_before","hbp_year_of_diagnosis","premature_heart_or_stroke_disease","diabetes_or_kidney_disease","tradition_medicine_use","previous_medical_complications","medical_history_other_health_complications","allergies_details","visit_end_date_time","drugs"],"orderby":[],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]}],"form_data":{"datasource":"16__table","viz_type":"table","slice_id":48,"granularity_sqla":"visit_date_time","time_grain_sqla":"P1D","time_range":"No
  filter","query_mode":"raw","groupby":[],"metrics":[],"all_columns":["client_id","client_name","gender","age","id_poor","national_id","covid_vacination_id","pmrs_id","nssf","ssn","passport_no","other_identifiers","village","commune","district","province","country","phone_number","occupation","place_of_birth","ethnicity","marital_status","education","visit_date_time","hf_code","hf_name","visit_type","visit_province","visit_district","payment_type","referred_from","address_zone","has_referral_letter","tb_symptom_presence","refferred_tb","waist_circumference","weight","height","bmi","systolic","diastolic","pulse_rate","temperature","respiratory","spo2","fasting_blood_sugar","random_blood_sugar","ogtt_h1","ogtt_h2","hb1ac","haemoglobin","albumin","ketones","total_cholesterol","low_density_lipoprotein","high_density_lipoprotein","triglycerides","creatinine","creatinine_clearance","proteinuria","potassium","ace_inhibitor","sodium","ast_asat","alt_alat","smoking","quit_smoking","physical_activity","alcohol","left_foot_exam","right_foot_exam","left_eye_exam","right_eye_exam","cardiovacscular_exam","uro_gen_exam","ent_exam","respiratory_exam","gastro_intestinal_exam","skin_extremities_examination","cns_exam","mental_state_exam","abdominal_exam","others_exam","cvd_score","diagnosis_one","diagnosis_two","other_health_conditions","current_medical_complications","other_health_complications","current_therapy","started_on_medicine","other_recomendations","follow_up_date","reason_for_referral","diagnosed_for_dm","dm_treatment_before","dm_year_of_diagnosis","diagnosed_for_hbp","hbp_treatment_before","hbp_year_of_diagnosis","premature_heart_or_stroke_disease","diabetes_or_kidney_disease","tradition_medicine_use","previous_medical_complications","medical_history_other_health_complications","allergies_details","visit_end_date_time","drugs"],"percent_metrics":[],"adhoc_filters":[],"order_by_cols":[],"row_limit":1000,"server_page_length":10,"include_time":false,"order_desc":true,"table_timestamp_format":"smart_date","show_cell_bars":false,"color_pn":true,"allow_rearrange_columns":true,"conditional_formatting":[],"extra_form_data":{},"dashboards":[10],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 52bda91a-f96f-4984-aaa6-d96ac6e50497
version: 1.0.0
dataset_uuid: 8480636a-399d-438b-a307-a2a1d160ed05
