slice_name: NCD HC EMR Raw Data
description: null
certified_by: null
certification_details: null
viz_type: table
params:
  datasource: 17__table
  viz_type: table
  slice_id: 49
  granularity_sqla: visit_date_time
  time_grain_sqla: P1D
  time_range: No filter
  query_mode: raw
  groupby: []
  metrics: []
  all_columns:
  - client_id
  - client_name
  - gender
  - age
  - id_poor
  - national_id
  - covid_vacination_id
  - pmrs_id
  - nssf
  - ssn
  - passport_no
  - other_identifiers
  - village
  - commune
  - district
  - province
  - country
  - phone_number
  - occupation
  - place_of_birth
  - ethnicity
  - marital_status
  - education
  - visit_date_time
  - hf_code
  - hf_name
  - visit_type
  - visit_province
  - visit_district
  - payment_type
  - referred_from
  - address_zone
  - has_referral_letter
  - screened_dm_hbp
  - known_hypertensive
  - known_hypertensive_meds_use
  - known_diabetic
  - diabetic_meds_use
  - current_therapy
  - hx_diabetes_and_heart_disease
  - hx_heart_disease
  - previous_medical_complications
  - other_health_complications
  - presence_of_allergies
  - allergies_details
  - waist_circumference
  - weight
  - height
  - bmi
  - systolic
  - diastolic
  - pulse_rate
  - temperature
  - fasting_blood_sugar
  - random_blood_sugar
  - ogtt
  - hb1ac
  - albumin
  - ketones
  - cholesterol
  - smoking
  - quit_smoking
  - physical_activity
  - alcohol
  - consultation_by
  - tele_consultation
  - foot_exam
  - foot_problem
  - tb_presence
  - tb_symptions
  - tb_referred
  - left_eye_exam
  - left_visual_acuity
  - left_eye_lids_eye_lashes
  - left_conjunctiva
  - left_cornea
  - left_pupil
  - left_lens
  - right_eye_exam
  - right_visual_acuity
  - right_eye_lids_eye_lashes
  - right_conjunctiva
  - right_cornea
  - right_pupil
  - right_lens
  - cvd_score
  - diagnosis_one
  - diagnosis_two
  - other_health_conditions
  - for_referral_criteria
  - referral_criteria
  - referred_to
  - hypertension_diagnosis
  - rf_hf_name
  - follow_up_cvd_score_risk_factors
  - follow_up_date
  - recommendations
  - started_on_medicine
  - visit_end_date_time
  - drugs
  percent_metrics: []
  adhoc_filters: []
  order_by_cols: []
  server_pagination: false
  row_limit: 1000
  server_page_length: 10
  order_desc: true
  table_timestamp_format: smart_date
  show_cell_bars: false
  color_pn: true
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 11
  annotation_layers: []
query_context: '{"datasource":{"id":17,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","granularity":"visit_date_time","filters":[],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["client_id","client_name","gender","age","id_poor","national_id","covid_vacination_id","pmrs_id","nssf","ssn","passport_no","other_identifiers","village","commune","district","province","country","phone_number","occupation","place_of_birth","ethnicity","marital_status","education","visit_date_time","hf_code","hf_name","visit_type","visit_province","visit_district","payment_type","referred_from","address_zone","has_referral_letter","screened_dm_hbp","known_hypertensive","known_hypertensive_meds_use","known_diabetic","diabetic_meds_use","current_therapy","hx_diabetes_and_heart_disease","hx_heart_disease","previous_medical_complications","other_health_complications","presence_of_allergies","allergies_details","waist_circumference","weight","height","bmi","systolic","diastolic","pulse_rate","temperature","fasting_blood_sugar","random_blood_sugar","ogtt","hb1ac","albumin","ketones","cholesterol","smoking","quit_smoking","physical_activity","alcohol","consultation_by","tele_consultation","foot_exam","foot_problem","tb_presence","tb_symptions","tb_referred","left_eye_exam","left_visual_acuity","left_eye_lids_eye_lashes","left_conjunctiva","left_cornea","left_pupil","left_lens","right_eye_exam","right_visual_acuity","right_eye_lids_eye_lashes","right_conjunctiva","right_cornea","right_pupil","right_lens","cvd_score","diagnosis_one","diagnosis_two","other_health_conditions","for_referral_criteria","referral_criteria","referred_to","hypertension_diagnosis","rf_hf_name","follow_up_cvd_score_risk_factors","follow_up_date","recommendations","started_on_medicine","visit_end_date_time","drugs"],"orderby":[],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{},"post_processing":[]}],"form_data":{"datasource":"17__table","viz_type":"table","slice_id":49,"granularity_sqla":"visit_date_time","time_grain_sqla":"P1D","time_range":"No
  filter","query_mode":"raw","groupby":[],"metrics":[],"all_columns":["client_id","client_name","gender","age","id_poor","national_id","covid_vacination_id","pmrs_id","nssf","ssn","passport_no","other_identifiers","village","commune","district","province","country","phone_number","occupation","place_of_birth","ethnicity","marital_status","education","visit_date_time","hf_code","hf_name","visit_type","visit_province","visit_district","payment_type","referred_from","address_zone","has_referral_letter","screened_dm_hbp","known_hypertensive","known_hypertensive_meds_use","known_diabetic","diabetic_meds_use","current_therapy","hx_diabetes_and_heart_disease","hx_heart_disease","previous_medical_complications","other_health_complications","presence_of_allergies","allergies_details","waist_circumference","weight","height","bmi","systolic","diastolic","pulse_rate","temperature","fasting_blood_sugar","random_blood_sugar","ogtt","hb1ac","albumin","ketones","cholesterol","smoking","quit_smoking","physical_activity","alcohol","consultation_by","tele_consultation","foot_exam","foot_problem","tb_presence","tb_symptions","tb_referred","left_eye_exam","left_visual_acuity","left_eye_lids_eye_lashes","left_conjunctiva","left_cornea","left_pupil","left_lens","right_eye_exam","right_visual_acuity","right_eye_lids_eye_lashes","right_conjunctiva","right_cornea","right_pupil","right_lens","cvd_score","diagnosis_one","diagnosis_two","other_health_conditions","for_referral_criteria","referral_criteria","referred_to","hypertension_diagnosis","rf_hf_name","follow_up_cvd_score_risk_factors","follow_up_date","recommendations","started_on_medicine","visit_end_date_time","drugs"],"percent_metrics":[],"adhoc_filters":[],"order_by_cols":[],"server_pagination":false,"row_limit":1000,"server_page_length":10,"include_time":false,"order_desc":true,"table_timestamp_format":"smart_date","show_cell_bars":false,"color_pn":true,"conditional_formatting":[],"extra_form_data":{},"dashboards":[11],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 43fdf069-6fb1-436f-bfbb-43cd28a650d4
version: 1.0.0
dataset_uuid: 6ce6fc9b-68dd-41b9-bc50-488d1285923e
