slice_name: "\u1785\u17C6\u1793\u17BD\u1793\u179F\u17D2\u178F\u17D2\u179A\u17B8\u1780\
  \u17D2\u1793\u17BB\u1784\u1798\u17BD\u1799\u1794\u17D2\u179A\u1797\u17C1\u1791\u1793\
  \u17C3\u1780\u17B6\u179A\u1798\u1780\u179B\u17C1\u1784 (# of Women per Visit Type)"
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 2__table
  viz_type: pivot_table_v2
  slice_id: 6
  granularity_sqla: date_started
  time_grain_sqla: P1D
  time_range: No filter
  groupbyColumns:
  - age_group
  groupbyRows:
  - referred_from_grouping
  metrics:
  - count per visit type
  metricsLayout: COLUMNS
  adhoc_filters:
  - expressionType: SIMPLE
    subject: referred_from_grouping
    operator: '!='
    operatorId: NOT_EQUALS
    comparator: N/A
    clause: WHERE
    sqlExpression: null
    isExtra: false
    isNew: false
    datasourceWarning: false
    filterOptionName: filter_hi45tjqvk3o_h1gz189xbgr
  row_limit: 1000
  order_desc: false
  aggregateFunction: Sum
  rowTotals: true
  colTotals: true
  transposePivot: true
  valueFormat: ~g
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 2
  annotation_layers: []
query_context: '{"datasource":{"id":2,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","granularity":"date_started","filters":[{"col":"referred_from_grouping","op":"!=","val":"N/A"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["age_group","referred_from_grouping"],"metrics":["count
  per visit type"],"orderby":[["count per visit type",true]],"annotation_layers":[],"row_limit":1000,"series_limit":0,"order_desc":false,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"2__table","viz_type":"pivot_table_v2","slice_id":6,"granularity_sqla":"date_started","time_grain_sqla":"P1D","time_range":"No
  filter","groupbyColumns":["age_group"],"groupbyRows":["referred_from_grouping"],"metrics":["count
  per visit type"],"metricsLayout":"COLUMNS","adhoc_filters":[{"expressionType":"SIMPLE","subject":"referred_from_grouping","operator":"!=","operatorId":"NOT_EQUALS","comparator":"N/A","clause":"WHERE","sqlExpression":null,"isExtra":false,"isNew":false,"datasourceWarning":false,"filterOptionName":"filter_hi45tjqvk3o_h1gz189xbgr"}],"row_limit":1000,"order_desc":false,"aggregateFunction":"Sum","rowTotals":true,"colTotals":true,"transposePivot":true,"valueFormat":"~g","date_format":"smart_date","rowOrder":"key_a_to_z","colOrder":"key_a_to_z","conditional_formatting":[],"extra_form_data":{},"dashboards":[2],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: 8a137f25-14a7-4a3e-a740-0cbd17ca1de1
version: 1.0.0
dataset_uuid: ae55d2c5-1889-45e0-899e-a54beba3e234
