slice_name: "\u17A2\u17D2\u1793\u1780\u1791\u17D2\u179A\u1791\u1784\u17CB\u179F\u17BB\
  \u1781\u1797\u17B6\u1796\u1797\u17BC\u1798\u17B7 \u179A\u1799\u17C8\u1796\u17C1\u179B\
  \u178A\u17C2\u179B\u178F\u17D2\u179A\u17BC\u179C\u1787\u17D2\u179A\u17BE\u179F\u179A\
  \u17BE\u179F (VHSG selected period)"
description: null
certified_by: null
certification_details: null
viz_type: pivot_table_v2
params:
  datasource: 6__table
  viz_type: pivot_table_v2
  slice_id: 18
  granularity_sqla: date_started
  time_grain_sqla: P1D
  time_range: No filter
  groupbyColumns:
  - age_group
  groupbyRows:
  - referred_from_grouping
  - gender
  metrics:
  - count per age group
  metricsLayout: COLUMNS
  adhoc_filters:
  - clause: WHERE
    comparator: null
    datasourceWarning: false
    expressionType: SIMPLE
    filterOptionName: filter_6ligwprivux_5sulfmbqz33
    isExtra: false
    isNew: false
    operator: IS NOT NULL
    operatorId: IS_NOT_NULL
    sqlExpression: null
    subject: referred_from_grouping
  row_limit: 10000
  order_desc: true
  aggregateFunction: Sum
  rowTotals: true
  colTotals: true
  transposePivot: false
  valueFormat: ~g
  date_format: smart_date
  rowOrder: key_a_to_z
  colOrder: key_a_to_z
  conditional_formatting: []
  extra_form_data: {}
  dashboards:
  - 6
  annotation_layers: []
query_context: '{"datasource":{"id":6,"type":"table"},"force":false,"queries":[{"time_range":"No
  filter","granularity":"date_started","filters":[{"col":"referred_from_grouping","op":"IS
  NOT NULL"}],"extras":{"time_grain_sqla":"P1D","having":"","where":""},"applied_time_extras":{},"columns":["age_group","referred_from_grouping","gender"],"metrics":["count
  per age group"],"orderby":[["count per age group",false]],"annotation_layers":[],"row_limit":10000,"series_limit":0,"order_desc":true,"url_params":{},"custom_params":{},"custom_form_data":{}}],"form_data":{"datasource":"6__table","viz_type":"pivot_table_v2","slice_id":18,"granularity_sqla":"date_started","time_grain_sqla":"P1D","time_range":"No
  filter","groupbyColumns":["age_group"],"groupbyRows":["referred_from_grouping","gender"],"metrics":["count
  per age group"],"metricsLayout":"COLUMNS","adhoc_filters":[{"clause":"WHERE","comparator":null,"datasourceWarning":false,"expressionType":"SIMPLE","filterOptionName":"filter_6ligwprivux_5sulfmbqz33","isExtra":false,"isNew":false,"operator":"IS
  NOT NULL","operatorId":"IS_NOT_NULL","sqlExpression":null,"subject":"referred_from_grouping"}],"row_limit":10000,"order_desc":true,"aggregateFunction":"Sum","rowTotals":true,"colTotals":true,"transposePivot":false,"valueFormat":"~g","date_format":"smart_date","rowOrder":"key_a_to_z","colOrder":"key_a_to_z","conditional_formatting":[],"extra_form_data":{},"dashboards":[6],"force":false,"result_format":"json","result_type":"full"},"result_format":"json","result_type":"full"}'
cache_timeout: null
uuid: fcdead1b-d063-462f-80f7-3bebfe4ef55c
version: 1.0.0
dataset_uuid: 6fa56ea7-aa49-46cd-8ae8-f8c5d141e0c9
