table_name: CCS Referral Status Query-dataset
main_dttm_col: null
description: null
default_endpoint: null
offset: 0
cache_timeout: null
schema: public
sql: "SELECT\n    f_facility AS \"Facility Name\",\n    f_district AS \"Facility District\"\
  ,\n    f_province AS \"Facility Province\",\n    referral_facility_name AS \"Referral\
  \ Facility Name\",\n    referral_facility_district AS \"Referral Facility District\"\
  ,\n    referral_facility_province AS \"Referral Facility Province\",\n    CASE \n\
  \        WHEN identifiers ~ '.*OpenMRS ID: (.*?)(,|$).*' THEN REGEXP_REPLACE(identifiers,\
  \ '.*OpenMRS ID: (.*?)(,|$).*', '\\1', 'g')\n        ELSE ''\n    END AS \"OpenMRS\
  \ ID\",\n    CONCAT_WS(' ', given_name, middle_name, family_name) AS \"Patient's\
  \ name\",\n    DATE_PART('year', age(visit_date, birthdate)) AS \"Age\",\n    CASE\
  \ \n        WHEN attributes ~ '.*Telephone Number: (.*?)(\\/|$).*' THEN REGEXP_REPLACE(attributes,\
  \ '.*Telephone Number: (.*?)(\\/|$).*', '\\1', 'g')\n        ELSE ''\n    END AS\
  \ \"Phone number\",\n    address_state_province AS \"Province/City\",\n    address_county_district\
  \ AS \"District/ Khan\",\n    address_city AS \"Commune/ Sangkat\",\n    address_1\
  \ AS \"Village\",\n    visit_date AS \"Visit date\",\n    cervical_cancer_reason_for_referral\
  \ AS \"Cervical cancer reason for referral\",\n    other_cervical_cancer_reason_for_referral\
  \ AS \"Other cervical cancer reason for referral\",\n    breast_cancer_reason_for_referral\
  \ AS \"Breast cancer reason for referral\",\n    other_breast_cancer_reason_for_referral\
  \ AS \"Other breast cancer reason for referral\"\nFROM (\n    SELECT\n        DISTINCT\
  \ obs_referral_centre.obs_id,\n        facility_address.state_province AS \"f_province\"\
  ,\n        facility_address.county_district AS \"f_district\",\n        facility_address.name\
  \ AS \"f_facility\",\n        TRIM(BOTH ' ' FROM split_part(obs_referral_centre.answer_coded,\
  \ '>', 1)) AS referral_facility_province,\n        TRIM(BOTH ' ' FROM split_part(obs_referral_centre.answer_coded,\
  \ '>', 2)) AS referral_facility_district,\n        TRIM(BOTH ' ' FROM split_part(obs_referral_centre.answer_coded,\
  \ '>', 3)) AS referral_facility_name,\n        patient_id,\n        given_name,\n\
  \        middle_name,\n        family_name,\n        identifiers,\n        birthdate,\n\
  \        address_state_province,\n        address_county_district,\n        address_city,\n\
  \        address_1,\n        attributes,\n        vi.date_started AS \"visit_date\"\
  ,\n        vi.type AS \"visit_type\",\n        obs_cervical_referral_reason.answer_coded\
  \ AS \"cervical_cancer_reason_for_referral\",\n        obs_cervical_referral_reason.answer_text\
  \ AS \"other_cervical_cancer_reason_for_referral\",\n        obs_breast_referral_reason.answer_coded\
  \ AS \"breast_cancer_reason_for_referral\",\n        obs_breast_referral_reason.answer_text\
  \ AS \"other_breast_cancer_reason_for_referral\",\n        CASE \n            WHEN\
  \ referral_visit.visit_uuid IS NOT NULL THEN 'Yes'\n            ELSE 'No'\n    \
  \    END AS \"fulfilled_referral\"\n    FROM patients pa\n    LEFT OUTER JOIN visits\
  \ vi ON vi.visit_voided = false AND vi.patient_uuid = pa.patient_uuid\n    LEFT\
  \ OUTER JOIN locations facility_address ON facility_address.uuid = vi.location_uuid\n\
  \    LEFT OUTER JOIN (\n        SELECT obs1.obs_id, obs1.visit_uuid, MAX(date_created),\
  \ STRING_AGG(obs1.answer_coded, ', ') AS answer_coded, obs1.encounter_uuid\n   \
  \     FROM observations obs1\n        WHERE obs1.obs_voided = false AND obs1.question_uuid\
  \ = '758b9dd8-b6d0-4ac2-b245-0e7bffb4693a' AND obs1.encounter_type = 'Cervical Cancer\
  \ Screening'\n        GROUP BY obs1.visit_uuid, obs1.question_uuid, obs1.answer_coded,\
  \ obs1.encounter_uuid, obs1.obs_id\n    ) AS obs_referral_centre ON obs_referral_centre.visit_uuid\
  \ = vi.visit_uuid\n    \n    LEFT OUTER JOIN (\n        SELECT obs2.visit_uuid,\
  \ MAX(obs2.date_created), STRING_AGG(obs2.answer_coded, ', ') AS answer_coded, obs2.encounter_uuid,\
  \ obs_other_reason.answer_text\n        FROM observations obs2\n        LEFT OUTER\
  \ JOIN observations obs_other_reason ON obs2.encounter_uuid = obs_other_reason.encounter_uuid\
  \ AND obs_other_reason.question_uuid = '12f61ec2-e0b1-420d-be7b-43a95bce6e4a'\n\
  \        WHERE obs2.obs_voided = false AND obs2.question_uuid = 'c158e3b2-edf9-4e0e-9e95-d36de1a51527'\n\
  \        GROUP BY obs2.visit_uuid, obs2.question_uuid, obs2.answer_coded, obs2.encounter_uuid,\
  \ obs_other_reason.answer_text\n    ) AS obs_cervical_referral_reason  ON obs_cervical_referral_reason.encounter_uuid\
  \ = obs_referral_centre.encounter_uuid\n    \n    LEFT OUTER JOIN (\n        SELECT\
  \ obs3.visit_uuid, MAX(obs3.date_created), obs3.answer_coded, obs3.encounter_uuid,\
  \ obs_other_reason2.answer_text\n        FROM observations obs3\n        LEFT OUTER\
  \ JOIN observations obs_other_reason2 ON obs_other_reason2.obs_voided = false AND\
  \ obs3.encounter_uuid = obs_other_reason2.encounter_uuid AND obs_other_reason2.question_uuid\
  \ = 'f984b718-d674-40c4-9ac4-8d22963e1933'\n        WHERE obs3.obs_voided = false\
  \ AND obs3.question_uuid = 'e676ab7f-13b0-4251-84fd-9874c80133b5'\n        GROUP\
  \ BY obs3.visit_uuid, obs3.question_uuid, obs3.answer_coded, obs3.encounter_uuid,\
  \ obs_other_reason2.answer_text\n    ) AS obs_breast_referral_reason ON obs_breast_referral_reason.encounter_uuid\
  \ = obs_referral_centre.encounter_uuid\n\n    LEFT OUTER JOIN visits referral_visit\
  \ ON referral_visit.visit_voided = false AND referral_visit.patient_uuid = pa.patient_uuid\
  \ AND DATE(referral_visit.date_started) >= DATE(vi.date_started) AND DATE(referral_visit.date_started)\
  \ <= DATE(vi.date_started + INTERVAL '7 days') AND referral_visit.location = TRIM(BOTH\
  \ ' ' FROM split_part(obs_referral_centre.answer_coded, '>', 3))\n\n    WHERE obs_referral_centre.answer_coded\
  \ IS NOT NULL\n\n) AS patient_info \nWHERE patient_info.visit_type IN ('Cervical\
  \ Cancer New Visit', 'Cervical Cancer Follow-up Visit') AND patient_info.fulfilled_referral\
  \ = 'No'\n"
params: null
template_params: null
filter_select_enabled: false
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
uuid: 412423af-0fdd-4e33-b15d-2b63a9e213e1
metrics:
- metric_name: count
  verbose_name: null
  metric_type: null
  expression: count(*)
  description: null
  d3format: null
  currency: null
  extra:
    warning_markdown: ''
  warning_text: null
columns:
- column_name: Referral Facility Name
  verbose_name: "\u1791\u17C5 - \u1798\u17BC\u179B\u178A\u17D2\u178B\u17B6\u1793\u179F\
    \u17BB\u1781\u17B6\u1797\u17B7\u1794\u17B6\u179B (\u1780\u17BC\u178A_\u1788\u17D2\
    \u1798\u17C4\u17C7) (To - Health facility (Code_Name))"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Referral Facility District
  verbose_name: "\u1791\u17C5 - \u179F\u17D2\u179A\u17BB\u1780\u1794\u17D2\u179A\u178F\
    \u17B7\u1794\u178F\u17D2\u178F\u17B7 (To - OD - Operational District)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Breast cancer reason for referral
  verbose_name: "\u1798\u17BC\u179B\u17A0\u17C1\u178F\u17BB\u1793\u17C3\u1780\u17B6\
    \u179A\u1794\u1789\u17D2\u1787\u17BC\u1793 (Reason of Referral - Breast cancer)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Cervical cancer reason for referral
  verbose_name: "\u1798\u17BC\u179B\u17A0\u17C1\u178F\u17BB\u1793\u17C3\u1780\u17B6\
    \u179A\u1794\u1789\u17D2\u1787\u17BC\u1793 (Reason of Referral - Cervical cancer)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Facility Name
  verbose_name: "\u1796\u17B8 - \u1798\u17BC\u179B\u178A\u17D2\u178B\u17B6\u1793\u179F\
    \u17BB\u1781\u17B6\u1797\u17B7\u1794\u17B6\u179B (\u1780\u17BC\u178A_\u1788\u17D2\
    \u1798\u17C4\u17C7) (From - Health facility (Code_Name))"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Facility District
  verbose_name: "\u1796\u17B8 - \u179F\u17D2\u179A\u17BB\u1780\u1794\u17D2\u179A\u178F\
    \u17B7\u1794\u178F\u17D2\u178F\u17B7 (From- OD - Operational District)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Referral Facility Province
  verbose_name: "\u1791\u17C5 - \u1781\u17C1\u178F\u17D2\u178F (To - Province)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Other breast cancer reason for referral
  verbose_name: "\"\u1795\u17D2\u179F\u17C1\u1784\u17D7\" (Other)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Other cervical cancer reason for referral
  verbose_name: "\"\u1795\u17D2\u179F\u17C1\u1784\u17D7\" (Other)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: OpenMRS ID
  verbose_name: "ID \u17A2\u178F\u17B7\u1790\u17B7\u1787\u1793 (EMR) (Patient ID (EMR))"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Commune/ Sangkat
  verbose_name: "\u17A2\u17B6\u179F\u1799\u178A\u17D2\u178B\u17B6\u1793 - \u1783\u17BB\
    \u17C6/\u179F\u1784\u17D2\u1780\u17B6\u178F\u17CB (Address - Commune)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Facility Province
  verbose_name: "\u1796\u17B8 - \u1781\u17C1\u178F\u17D2\u178F (From - Province)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Patient's name
  verbose_name: "\u1782\u17C4\u178F\u17D2\u178F\u1793\u17B6\u1798 -\u1793\u17B6\u1798\
    \ \u17A2\u178F\u17B7\u1790\u17B7\u1787\u1793 (Client's Surename-Name)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Province/City
  verbose_name: "\u17A2\u17B6\u179F\u1799\u178A\u17D2\u178B\u17B6\u1793 - \u1781\u17C1\
    \u178F\u17D2\u178F (Address - Province)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Village
  verbose_name: "\u17A2\u17B6\u179F\u1799\u178A\u17D2\u178B\u17B6\u1793 - \u1797\u17BC\
    \u1798\u17B7 (Address - Village)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: District/ Khan
  verbose_name: "\u17A2\u17B6\u179F\u1799\u178A\u17D2\u178B\u17B6\u1793 \u179F\u17D2\
    \u179A\u17BB\u1780 (Address - District)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Visit date
  verbose_name: "\u1780\u17B6\u179B\u1794\u179A\u17B7\u1785\u17D2\u1786\u17C1\u1791\
    \u178A\u17C2\u179B\u17A2\u178F\u17B7\u1790\u17B7\u1787\u1793\u1791\u17C5\u178F\
    \u17B6\u1798\u1780\u17B6\u179A\u1794\u1789\u17D2\u1787\u17BC\u1793 (Visit Date\
    \ at Hospital)"
  is_dttm: true
  is_active: true
  type: DATETIME
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Age
  verbose_name: "\u17A2\u17B6\u1799\u17BB (\u1786\u17D2\u1793\u17B6\u17C6) (Age (Years))"
  is_dttm: false
  is_active: true
  type: FLOAT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Phone number
  verbose_name: "\u179B\u17C1\u1781\u1791\u17BC\u179A\u179F\u17D0\u1796\u17D2\u1791\
    \ (Phone Number)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
version: 1.0.0
database_uuid: 42834407-4570-4111-8bf6-4f7080413333
