table_name: NCD Missed Appointments Query-dataset
main_dttm_col: null
description: null
default_endpoint: null
offset: 0
cache_timeout: null
schema: public
sql: "SELECT\n    f_facility AS \"Facility Name\",\n    f_district AS \"Facility District\"\
  ,\n    f_province AS \"Facility Province\",\n    CASE \n        WHEN identifiers\
  \ ~ '.*OpenMRS ID: (.*?)(,|$).*' THEN REGEXP_REPLACE(identifiers, '.*OpenMRS ID:\
  \ (.*?)(,|$).*', '\\1', 'g')\n        ELSE ''\n    END AS \"OpenMRS ID\",\n    CONCAT_WS('\
  \ ', given_name, middle_name, family_name) AS \"Patient's name\",\n    gender AS\
  \ \"Gender\",\n    DATE_PART('year', age(visit_date, birthdate)) AS \"Age\",\n \
  \   CASE \n        WHEN attributes ~ '.*Telephone Number: (.*?)(\\/|$).*' THEN REGEXP_REPLACE(attributes,\
  \ '.*Telephone Number: (.*?)(\\/|$).*', '\\1', 'g')\n        ELSE ''\n    END AS\
  \ \"Phone number\",\n    address_1 AS \"Village\",\n    address_city AS \"Commune/\
  \ Sangkat\",\n    address_county_district AS \"District/ Khan\",\n    address_state_province\
  \ AS \"Province/City\",\n    DATE(followup_date) AS \"Appointment date\",\n    followup_for\
  \ AS \"Appointment/follow-up reasaon\",\n    '' AS \"Notes\"\nFROM (\n    SELECT\n\
  \        DISTINCT obs_followup_for.obs_id,\n        facility_address.state_province\
  \ AS \"f_province\",\n        facility_address.county_district AS \"f_district\"\
  ,\n        facility_address.name AS \"f_facility\",\n        given_name,\n     \
  \   middle_name,\n        family_name,\n        identifiers,\n        birthdate,\n\
  \        gender,\n        address_state_province,\n        address_county_district,\n\
  \        address_city,\n        address_1,\n        attributes,\n        vi.date_started\
  \ AS \"visit_date\",\n        vi.type AS \"visit_type\",\n        obs_followup_date.answer_datetime\
  \ AS \"followup_date\",\n        obs_followup_for.answer_coded AS \"followup_for\"\
  ,\n        obs_appointment_notes.answers_coded AS \"appointment_notes\",\n     \
  \   CASE \n            WHEN followup_visit.visit_uuid IS NOT NULL THEN 'Yes'\n \
  \           ELSE 'No'\n        END AS \"fulfilled_appointment\"\n    FROM patients\
  \ pa\n    LEFT OUTER JOIN visits vi ON vi.visit_voided = false AND vi.patient_uuid\
  \ = pa.patient_uuid AND vi.type IN ('NCD New Visit')\n    LEFT OUTER JOIN locations\
  \ facility_address ON facility_address.uuid = vi.location_uuid\n\n    LEFT OUTER\
  \ JOIN (\n        SELECT obs2.visit_uuid, MAX(obs2.obs_date_time), obs2.answer_datetime,\
  \ obs2.encounter_uuid\n        FROM observations obs2\n        WHERE obs2.obs_voided\
  \ = false AND obs2.question_uuid = 'e9c145c1-f4e9-4c34-b237-da069939dc38' AND obs2.encounter_type\
  \ IN ('Health Center - NCD Screening')\n        GROUP BY obs2.visit_uuid, obs2.question_uuid,\
  \ obs2.answer_datetime, obs2.encounter_uuid\n    ) AS obs_followup_date ON obs_followup_date.visit_uuid\
  \ = vi.visit_uuid\n\n    LEFT OUTER JOIN (\n        SELECT obs1.obs_id, obs1.visit_uuid,\
  \ STRING_AGG(obs1.answer_coded, ', ') AS answer_coded, obs1.encounter_uuid\n   \
  \     FROM observations obs1\n        WHERE obs1.obs_voided = false AND obs1.question_uuid\
  \ = '2e27bbf9-d744-46a2-a7d4-cecd33c28b8a'\n        GROUP BY obs1.visit_uuid, obs1.question_uuid,\
  \ obs1.answer_coded, obs1.encounter_uuid, obs1.obs_id\n    ) AS obs_followup_for\
  \ ON obs_followup_date.encounter_uuid = obs_followup_for.encounter_uuid\n    \n\
  \    LEFT OUTER JOIN (\n        SELECT obs3.visit_uuid, STRING_AGG(obs3.answer_coded,\
  \ ', ') AS answers_coded, obs3.encounter_uuid\n        FROM observations obs3\n\
  \        WHERE obs3.obs_voided = false AND obs3.question_uuid = '9f7c8739-3ea3-4f7f-8648-d6c36fef7be2'\n\
  \        GROUP BY obs3.visit_uuid, obs3.encounter_uuid\n    ) AS obs_appointment_notes\
  \  ON obs_appointment_notes.encounter_uuid = obs_followup_for.encounter_uuid\n\n\
  \    LEFT OUTER JOIN visits followup_visit ON followup_visit.visit_voided = false\
  \ AND followup_visit.patient_uuid = pa.patient_uuid AND DATE(followup_visit.date_started)\
  \ >= DATE(obs_followup_date.answer_datetime) AND DATE(followup_visit.date_started)\
  \ <= DATE(obs_followup_date.answer_datetime + INTERVAL '7 days') AND followup_visit.type\
  \ IN ('NCD Follow-up Visit')\n\n    WHERE pa.person_voided = false AND obs_followup_for.answer_coded\
  \ IS NOT NULL\n\n) AS patient_info\n\nWHERE patient_info.fulfilled_appointment =\
  \ 'No'"
params: null
template_params: null
filter_select_enabled: false
fetch_values_predicate: null
extra: null
normalize_columns: false
always_filter_main_dttm: false
uuid: ffccf504-e9e6-4312-916b-51489c810249
metrics:
- metric_name: count
  verbose_name: null
  metric_type: null
  expression: count(*)
  description: null
  d3format: null
  currency: null
  extra:
    warning_markdown: ''
  warning_text: null
columns:
- column_name: Commune/ Sangkat
  verbose_name: "\u17A2\u17B6\u179F\u1799\u178A\u17D2\u178B\u17B6\u1793 - \u1783\u17BB\
    \u17C6/\u179F\u1784\u17D2\u1780\u17B6\u178F\u17CB (Address - Commune)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: District/ Khan
  verbose_name: "\u17A2\u17B6\u179F\u1799\u178A\u17D2\u178B\u17B6\u1793 - \u179F\u17D2\
    \u179A\u17BB\u1780 (Address - District)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Province/City
  verbose_name: "\u17A2\u17B6\u179F\u1799\u178A\u17D2\u178B\u17B6\u1793 - \u1781\u17C1\
    \u178F\u17D2\u178F (Address - Province)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Village
  verbose_name: "\u17A2\u17B6\u179F\u1799\u178A\u17D2\u178B\u17B6\u1793 - \u1797\u17BC\
    \u1798\u17B7 (Address - Village)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Facility Name
  verbose_name: "\u1788\u17D2\u1798\u17C4\u17C7\u1793\u17B7\u1784\u179B\u17C1\u1781\
    \u1780\u17BC\u178A\u1798\u17BC\u179B\u178A\u17D2\u178B\u17B6\u1793\u179F\u17BB\
    \u1781\u17B6\u1797\u17B7\u1794\u17B6\u179B (Health Facility's Name)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Appointment date
  verbose_name: "\u1780\u17B6\u179A\u1794\u179A\u17B7\u1785\u17D2\u1786\u17C1\u1791\
    \u178E\u178F\u17CB (Date Of Appointment)"
  is_dttm: true
  is_active: true
  type: DATE
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Facility Province
  verbose_name: "\u1798\u1793\u17D2\u1791\u17B8\u179A\u179F\u17BB\u1781\u17B6\u1797\
    \u17B7\u1794\u17B6\u179B\u1781\u17C1\u178F\u17D2\u178F (Provincial Health Department)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Patient's name
  verbose_name: "\u1788\u17D2\u1798\u17C4\u17C7\u17A2\u17D2\u1793\u1780\u1787\u17C6\
    \u1784\u17BA (Patient Name)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Appointment/follow-up reasaon
  verbose_name: "\u1780\u17B6\u179A\u178E\u178F\u17CB\u178F\u17B6\u1798\u178A\u17B6\
    \u1793 (Appointment/follow-up reason)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: OpenMRS ID
  verbose_name: "\u17A2\u178F\u17D2\u178F\u179B\u17C1\u1781\u17A2\u17D2\u1793\u1780\
    \u1787\u17C6\u1784\u17BA (Client ID)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Facility District
  verbose_name: "\u179F\u17D2\u179A\u17BB\u1780\u1794\u17D2\u179A\u178F\u17B7\u1794\
    \u178F\u17D2\u178F\u17B7 (Operational District)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Phone number
  verbose_name: "\u179B\u17C1\u1781\u1791\u17BC\u179A\u179F\u1796\u17D2\u1791 (Phone\
    \ number)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Age
  verbose_name: "\u17A2\u17B6\u1799\u17BB (Age)"
  is_dttm: false
  is_active: true
  type: FLOAT
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Gender
  verbose_name: "\u1797\u17C1\u1791 (Gender)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
- column_name: Notes
  verbose_name: "\u1780\u17C6\u178E\u178F\u17CB\u179F\u1798\u17D2\u1782\u17B6\u179B\
    \u17CB (Notes)"
  is_dttm: false
  is_active: true
  type: STRING
  advanced_data_type: null
  groupby: true
  filterable: true
  expression: null
  description: null
  python_date_format: null
  extra:
    warning_markdown: null
version: 1.0.0
database_uuid: 42834407-4570-4111-8bf6-4f7080413333
